# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on: ["push", "pull_request"]

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12.2
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: gist
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        ports:
          - 5432:5432


    strategy:
      matrix:
        node-version: [10.x, 12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    env:
      NODE_ENV: test
      DATABASE_URL_TEST: postgres://postgres:postgres@localhost:5432/gist
      CLIENT_URL: https://www.youtube.com/watch?v=KxGRhd_iWuE

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: yarn --frozen-lockfile
    - run: yarn run test
